GursuYapi/urls.py
from django.contrib import admin
from django.urls import path,include
from order import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.dashboard),
    path('order/',include('order.urls')),
    path('about/',views.about, name='about'),
    path('user/',include('user.urls')),
    path('workflow/',include('workflow.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="order"

urlpatterns = [
    path('dashboard/<str:departman>/<str:list_filter>', views.dashboard, name='dashboard'),
 #   path('dashboard2/', views.dashboard2, name='dashboard2'),
    
    path('orderAdd3/', views.orderAdd3, name='orderAdd3'),
    path('orderList/<str:list_filter>', views.orderList, name='orderList'),
    path('orderView/<int:id>', views.orderView, name='orderView'),
    path('orderUpdate/<int:id>', views.orderUpdate, name='orderUpdate'),
    path('orderDelete/<int:id>', views.orderDelete, name='orderDelete'),
    path('orderAddProduct/<int:id>', views.orderAddProduct, name='orderAddProduct'),
    path('orderDeleteProduct/<int:id>', views.orderDeleteProduct, name='orderDeleteProduct'),
    path('orderApproved/<int:id>', views.orderApproved, name='orderApproved'),
    path('orderAdresSecim/<str:fs>/<str:es>/<int:order_id>/<int:address_id>', views.orderAdresSecim, name='orderAdresSecim'),
    path('orderSiparisFisi/<int:id>', views.orderSiparisFisi, name='orderSiparisFisi'),
    path('dosyaEkle/<int:order_id>/<int:workflow_id>', views.dosyaEkle, name='dosyaEkle'),
    path('siparisPaketi/<int:order_id>/<int:workflow_id>', views.siparisPaketi, name='siparisPaketi'),
    path('orderPacketDelete/<int:order_product_id>', views.orderPacketDelete, name='orderPacketDelete'),
    path('orderPaketOnayla/<int:order_id>/<int:workflow_id>', views.orderPaketOnayla, name='orderPaketOnayla'),
    path('uretim_depo', views.uretim_depo, name='uretim_depo'),

    path('customerAdd/',views.customerAdd,name='customerAdd'),
    path('customerAddressAdd/<int:id>',views.customerAddressAdd,name='customerAddressAdd'),
    path('customerAddressUpdate/<int:id>',views.customerAddressUpdate,name='customerAddressUpdate'),
    path('customerAddressActivation/<int:id>',views.customerAddressActivation,name='customerAddressActivation'),
   # path('customerAdd2/',views.customerAdd2,name='customerAdd2'),
    path('customerList/',views.customerList,name='customerList'),
    path('customerView/<int:id>',views.customerView,name='customerView'),
    path('customerUpdate/<int:id>',views.customerUpdate,name='customerUpdate'),
    path('customerDelete/<int:id>',views.customerDelete,name='customerDelete'),
    
    path('productAdd/',views.productAdd,name='productAdd'),
    path('productList/',views.productList,name='productList'),
    path('productUpdate/<int:id>',views.productUpdate,name='productUpdate'),
    path('productDeactive/<int:id>',views.productDeactive,name='productDeactive'),
    path('productActive/<int:id>',views.productActive,name='productActive'),
    path('ajax/productDropList/', views.productDropList, name='ajax_productDropList'),
    path('ajax/orderDropList/', views.orderDropList, name='ajax_orderDropList'),
    path('ajax/colorList/', views.colorList, name='ajax_colorList'),
    path('ajax/categoryDropList/', views.categoryDropList, name='ajax_categoryDropList'),
    
    path('planlama/<str:list_filter>',views.planlama,name='planlama'),
    

    path('reservationList/',views.reservationList,name='reservationList'),
    path('takvim/<int:day>',views.takvim,name='takvim'),
    path('takvim_v2/',views.takvim_v2,name='takvim_v2'),
    path('events/',views.events,name='events'),
    path('events_data/',views.events_data,name='events_data'),
    path('reservationView/<int:id>',views.reservationView,name='reservationView'),
    path('reservationDelete/<int:reservation_id>',views.reservationDelete,name='reservationDelete'),

    #path('workflowCompleted/<int:id>',views.workflowCompleted,name='workflowCompleted'),
    path('workflowView/<int:id>',views.workflowView,name='workflowView'),
    path('workflowPlanla/<int:id>',views.workflowPlanla,name='workflowPlanla'),
    path('workflowStatuUpdate/<int:id>/<int:statu>',views.workflowStatuUpdate,name='workflowStatuUpdate'),
    path('yeniWorkflow/<int:workflow_id>',views.yeniWorkflow,name='yeniWorkflow'),

    path('problemAdd/<int:id>',views.problemAdd,name='problemAdd'),
    path('problemAddFull/',views.problemAddFull,name='problemAddFull'),
    path('problemList/',views.problemList,name='problemList'),
    path('problemView/<int:id>',views.problemView,name='problemView'),

    path('rapor', views.rapor, name='rapor'),
    path('data_aylik_satis',views.data_aylik_satis,name='data_aylik_satis'),
    path('data_aylik_satis_tutar',views.data_aylik_satis_tutar,name='data_aylik_satis_tutar'),

    path('test/',views.test,name='test'),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="user"

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('userAdd/', views.userAdd, name='userAdd'),
    path('userList/', views.userList, name='userList'),
    path('userView/<int:id>', views.userView, name='userView'),
    path('userUpdate/<int:id>', views.userUpdate, name='userUpdate'),
    path('userDelete/<int:id>', views.userDelete, name='userDelete'),
    path('userYetki/<int:id>/<str:islem>/<str:perm>',views.userYetki,name ='userYetki'),
    path('userChangePassword/<int:id>', views.userChangePassword, name='userChangePassword'),
    path('logView/', views.logView, name='logView'),
    path('yetkiYok/', views.yetkiYok, name='yetkiYok'),
]

workflow/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="workflow"

urlpatterns = [
    path('workflowList/', views.workflowList, name='workflowList'),

    
    
]

order/models.py
from django.db import migrations,models
from user.models import User,Employee,Sube
from ckeditor.fields import RichTextField
from django.utils import timezone
# Create your models here.


class OrderStatu(models.Model):
    number = models.IntegerField(verbose_name="Durum Numarası")
    title =  models.CharField(verbose_name="Order Statu",max_length=50)
    aciklama =  models.CharField(verbose_name="Açıklama",max_length=50,null=True)
    def __str__(self):
        return self.title

class Order (models.Model):
    """
    orderTypeChoise = (
        ("U","Uretim"),
        ("S","Sevk"),
        ("M","Montaj"),
        ("D","Depo Teslim"),
    )
    satisKanalSecenek = (
        ("Perakende","Perakende"),
        ("Toptan","Toptan"),
        ("Proje","Proje")
    )
    """
    planlamaSecenek = (
        ("En Hızlı","En Hızlı"),
        ("Müş.den Haber Bekle","Müş.den Haber Bekle"),
        ("Müsaitliğimize Göre","Müsaitliğimize Göre")
    )
    customer = models.ForeignKey("Customer",on_delete=models.CASCADE,verbose_name="Müşteri")
    #TODO user bilgisi eklenecek
    create_date = models.DateTimeField()
    content = RichTextField(verbose_name="Açıklama",blank =True,null=True)
    order_image = models.FileField(blank =True,null=True,verbose_name="Ölçü/Üretim Dökümanı")
    stok = models.CharField(max_length=1,choices = [('1', 'Var'), ('0', 'Yok')],verbose_name="Stok Durumu",default="0")
    #order_type = models.CharField(max_length=1,choices = orderTypeChoise,verbose_name="Sipariş Tipi")
    #statu = models.CharField(max_length=2,choices = status,verbose_name="Sipariş Durumu",default="0")
    statu = models.ForeignKey(OrderStatu,on_delete=models.PROTECT,default=23)
    iskonto = models.IntegerField(default=0,verbose_name="İskonto Oranı(%)")
    tahmini_tarih_min = models.DateField(null=True,verbose_name="En erken teslim (yyyy-mm-dd)")
    tahmini_tarih_max = models.DateField(null=True,verbose_name="En geç teslim (yyyy-mm-dd)")
    completed_date = models.DateTimeField(blank =True,null=True)
        
    sevk_adres = models.IntegerField(verbose_name="Sevk Adresi",null=True)
    fatura_adres = models.IntegerField(verbose_name="Fatura Adresi",null=True)
    
    planlama_sekli = models.CharField(max_length=20,choices = planlamaSecenek,verbose_name="Planlama Şekli",default="En Hızlı")
    sube = models.ForeignKey(Sube,on_delete=models.PROTECT, verbose_name="Şube")
    siparis_paketi = models.BooleanField(verbose_name="siparis paketi statu",default=False)
    
    def __str__(self):
        #return self.customer.customer_name
        title= self.customer.customer_name+"_"+str(self.create_date)[:10]
        return title

class Customer(models.Model):
    satisKanalSecenek = (("Perakende","Perakende"),("Toptan","Toptan"),("Proje","Proje"))
    customer_type=(("Şahıs","Şahıs"),("Kurumsal","Kurumsal")    )

    customer_name = models.CharField(max_length=50,verbose_name="MÜŞTERİ ADI")
    telephone = models.CharField(max_length=50,verbose_name="TELEFON")
    email = models.CharField( max_length=254,verbose_name="EMAIL")
    created_date = models.DateTimeField()
    active = models.CharField(max_length=1,default="1",verbose_name="Aktif")
    vergi_no = models.IntegerField(verbose_name="Vergi/TC no",default=0,null=True)
    customer_type = models.CharField(max_length=10,choices = customer_type,verbose_name="Şahıs/Kurumsal",default=customer_type[0][1])
    vergi_dairesi = models.CharField(max_length=70,verbose_name="Vergi Dairesi",default="Fethiye VD.")
    satis_kanali = models.CharField(max_length=10,choices = satisKanalSecenek,verbose_name="Satış Kanalı",default="Perakende")

    def __str__(self):  # müşterileri listelerken gözükmesini istediğimiz isim
        return self.customer_name

    ########################################
    ### kayıt sırasında buyuk harfe cevirerek kayıt tamamlanır
    def save(self, force_insert=False, force_update=False): 
        self.customer_name = self.customer_name.upper() 
        super(Customer, self).save(force_insert, force_update)


class Address (models.Model):
    customer = models.ForeignKey("Customer",on_delete=models.CASCADE,verbose_name="Müşteri ID")
    ulke = models.CharField( max_length=30,verbose_name="ULKE",default="Türkiye")
    il = models.CharField( max_length=30,verbose_name="IL")
    ilce = models.CharField( max_length=30,verbose_name="İLÇE")
    mahalle = models.CharField( max_length=30,verbose_name="MAHALLE")
    adres = models.CharField( max_length=100,verbose_name="ADRES")
    map_link = models.CharField( max_length=100,verbose_name="GOOGLE MAP")
    aciklama = models.CharField( max_length=10,verbose_name="Açıklama(kısa/kod)")
    active = models.BooleanField(default=True)
    def __str__(self):  # listelerken gözükmesini istediğimiz isim
        return self.aciklama
    ########################################
    ### kayıt sırasında buyuk harfe cevirerek kayıt tamamlanır
    def save(self, force_insert=False, force_update=False): 
        self.ulke = self.ulke.upper() 
        self.il = self.il.upper() 
        self.ilce = self.ilce.upper() 
        self.mahalle = self.mahalle.upper() 
        self.adres = self.adres.upper() 
        super(Address, self).save(force_insert, force_update)

class OrderPackets(models.Model):
    orderTypeChoise = (
            ("U","Uretim"),
            ("S","Sevk"),
            ("M","Montaj"),
            ("D","Depo Teslim"),
        )
    order_type = models.CharField(max_length=1,choices = orderTypeChoise,verbose_name="Sipariş Tipi")
    status = models.BooleanField(default=False)
    #order_id = models.IntegerField(null=True,blank=True)
    uretim = models.BooleanField(default=False,verbose_name="Üretim var/yok")

class Workflow(models.Model):
    departments = (
        
        ("10000","Finans"),
        ("20000","Mali ve İdari işler"),
        ("30000","Satış"),
        ("31000","Saha Görevlisi"),
        ("40000","Operasyon"),
        ("41000","Planlama"),
        ("42000","Üretim"),
        ("43000","Depo"),
        ("44000","Montaj"),
        
    )
    """
    workflow_status = (
            ("10","Beklemede"),
            ("20","Çalışılıyor"),
            ("30","İptal edildi"),
            ("40","Tamamlandı"),)
    """
    
    order = models.ForeignKey(Order, on_delete=models.CASCADE,default=1)
    department = models.CharField(max_length=10,choices = departments,verbose_name="Departman")
    revision    = models.IntegerField(verbose_name="Revizyon",default=1)
    approve_user_id = models.IntegerField(verbose_name="İşi onaylayan kullanıcı",blank=True, null=True)
    completed_user_id = models.IntegerField(verbose_name="İşi yapan Kullanıcı",blank=True, null=True)
    #status = models.CharField(max_length=10,choices = workflow_status,verbose_name="Durum",default="10")
    status = models.ForeignKey(OrderStatu,on_delete=models.PROTECT)
    comment = models.CharField(max_length=50,verbose_name="Açıklama",default="test")
    created_date =models.DateTimeField()
    planed_date =models.DateTimeField(blank=True, null=True)
    completed_date =models.DateTimeField(blank=True, null=True)
    started_date =models.DateTimeField(blank=True, null=True)
    fisNo = models.IntegerField(verbose_name="Fiş NO",default=1,null=True)
    siparis_paketi = models.ForeignKey(OrderPackets,on_delete=models.PROTECT,blank=True, null=True)

class ProductCategory(models.Model):
    title = models.CharField(max_length=150, unique=True)
    main_category = models.CharField(max_length=2,default=1)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

class UrunGrubu(models.Model):
    title = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.title

class ProductType(models.Model):
    title = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.title

class Marka(models.Model):
    title = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=150)

    def __str__(self):
        return self.title

class Product(models.Model):
    unit_type = (
            ("AD","AD"),
            ("TN","TN"),
            ("M2","M2"),
            ("PK","PK"),
            ("TK","TK"),
            ("MT","MT"),
            ("BY","BY"),
            ("M3","M3"),
            ("KG","KG"),
       )
    urun_kodu = models.CharField(max_length=100,verbose_name="Ürün Kodu",blank=True, null=True)
    product_name = models.CharField(max_length=200,verbose_name="Ürün adı")
    marka = models.ForeignKey(Marka,on_delete=models.CASCADE,verbose_name="Urun Grubu",default=1)
    unit = models.CharField(max_length=10,choices=unit_type,verbose_name="Birim",default="AD")
    urun_grubu = models.ForeignKey(UrunGrubu,on_delete=models.CASCADE,verbose_name="Urun Grubu",default=1)
    #product_type =models.ForeignKey(ProductType,on_delete=models.CASCADE,verbose_name="Product Type",default=1)
    montaj_sabiti = models.IntegerField(verbose_name="Montaj Sabiti",default=0)
    birim_fiyat = models.IntegerField(verbose_name="Birim Fiyat" ,default=0)
    product_category = models.ForeignKey(ProductCategory,on_delete=models.CASCADE,verbose_name="Kategori",default=1)
    created_date = models.DateTimeField()
    active = models.BooleanField(default=True)
    #def __str__(self):    
    #    return self.product_category.title +"-"+ self.product_name
    ########################################
    ### kayıt sırasında buyuk harfe cevirerek kayıt tamamlanır
    def save(self, force_insert=False, force_update=False): 
        self.product_name = self.product_name.upper() 
        super(Product, self).save(force_insert, force_update)

class ProductColor(models.Model):
    renk_kodu = models.CharField(max_length=20,verbose_name="Renk",blank=True)
    product_category = models.ForeignKey(ProductCategory,on_delete=models.CASCADE,verbose_name="Kategori",default=1)
    def __str__(self):    

workflow/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Workflow(models.Model):
    
    order_id= models.CharField(max_length=10,verbose_name="Order ID")
    department = models.CharField(max_length=10,verbose_name="Order ID")
    revision    = models.IntegerField(max_length=2,verbose_name="Revizyon")
    approve_user_id = models.IntegerField(max_length=6,verbose_name="İşi onaylayan kullanıcı")
    completed_user_id = models.IntegerField(max_length=6,verbose_name="İşi yapan Kullanıcı")
    status = models.CharField(max_length=10,verbose_name="Order ID")
    created_date =models.DateField(auto_now=True)
    planed_date =models.DateField(blank=True, null=True)
    completed_date =models.DateField(blank=True, null=True)

workflow/forms.py
from django import forms
from django.contrib.auth.models import User

class WorkflowForm(forms.Form){

    departments = (
        ("11","Satış"),
        ("10000","Finans"),
        ("20000","Mali ve İdari işler"),
        ("30000","Satış"),
        ("31000","Saha Görevlisi"),
        ("40000","Operasyon"),
        ("41000","Planlama"),
        ("42000","Üretim"),
        ("43000","Depo"),
        ("44000","Montaj"),
        
    )
    workflow_status = (
            ("10","Beklemede"),
            ("20","Çalışılıyor"),
            ("30","İptal edildi"),
            ("40","Tamamlandı"),
            
    )


}

workflow/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

def workflowList(request):
    return  render(request,'workflow.html')

templates/colorList.html
<option value="">---------</option>
{% for color in colors %} 
<option value="{{ color.id }}" title ="{{ color.renk_kodu }}">{{ color.renk_kodu |truncatechars:50}}</option>
{% endfor %}

templates/orderAdd2.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div >
    <h3> 
            Sipariş Girişi
            <a href="/order/customerAdd">
                <button class="btn btn-success btn-sm">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag-plus" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 7.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0v-1.5H6a.5.5 0 0 1 0-1h1.5V8a.5.5 0 0 1 .5-.5z"/>
                    <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                  </svg>  Müşteri EKLE
                </button>
              </a>
            
    </h3>   
   
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<script>

    $(document).ready(function () {
            $('#tahmini_tarih_min').datetimepicker({
                format: 'YYYY-MM-DD',
                useCurrent: true,
                keepOpen: true,
                allowInputToggle: true,
                
                ignoreReadonly: true,
                showTodayButton: true,
                viewMode: 'days'
            });
            $('#id_tahmini_tarih_max').datetimepicker({
                format: 'YYYY-MM-DD',
                useCurrent: true,
                keepOpen: true,
                allowInputToggle: true,
                
                ignoreReadonly: true,
                showTodayButton: true,
                viewMode: 'days'
            });
            $('#divEndDate').datetimepicker({
                format: 'YYYY-MM-DD',
                useCurrent: false,
                keepOpen: true,
                allowInputToggle: true,
                maxDate: new Date(),
                ignoreReadonly: true,
                showTodayButton: true,
                viewMode: 'days'
            });
            $('#id_tahmini_tarih_min').datetimepicker({
                format: 'YYYY-MM-DD',
                useCurrent: true,
                keepOpen: true,
                allowInputToggle: true,
                
                ignoreReadonly: true,
                showTodayButton: true,
                viewMode: 'days'
            });
            

    });
    
    </script>
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}

        <div class="row">
            <div class="form-group col-md-3 mb-0">
              {{ form.customer|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
              {{ form.order_type|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.order_image|as_crispy_field }}
            </div>
        </div>
        
        <div class="row" >
            
            <div class="form-group col-md-6 mb-0">
                <div class="row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.stok|as_crispy_field }}

                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.iskonto|as_crispy_field }}

                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.satis_kanali|as_crispy_field }}

                    </div>
                    <div class="form-group col-md-6 mb-0">
                       
                    </div>
                </div>
                <br><br>
                <div class="row">
                    <div  class="col-md-6 mb-0">
                        Tahmini en erken tarih  <br>
                        <input type="date" name="tahmini_tarih_min" class="input-sm" placeholder="Tarih">
                    </div>
                    <div  class="form-group col-md-6 mb-0">
                 
                        Tahmini en geç tarih  <br>
                        <input type="date" name="tahmini_tarih_max" class="input-sm" placeholder="Tarih">
                    </div>
                </div>  
               

            </div>
            <div class="form-group col-md-6 mb-0" style ="height: 150px;">
                {{ form.content|as_crispy_field }}
            </div>
            
        </div>

        <br>
        <button type="submit" class="btn btn-warning">Giriş</button>
    </form>
</div>
{% endblock body %}

templates/siparisPaketi.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<form method="post" >
    {% csrf_token %}
 <div class="container">
    <h1 style="margin:10px auto 50px auto; text-align:center">Sipariş Paket seçimi</h1>
    <div class="row">
      <div class="col-sm-5">
        Gruplanmamış Ürünler
        <select name="from" id="undo_redo" class="form-control" size="8" multiple="multiple">
            {% for product in products %}
            <option value="{{ product.id}}"> {{ product.product.product_name}} </option>
        {% endfor %}
        </select>
      </div>
      <div class="col-sm-1">
          <br><br>
        <button type="button" id="undo_redo_undo" class="btn btn-primary btn-block">undo</button>
        <!-- bu buton çalışırken sorun cıkardı. hepsini attığımızda kayıt yapmadı. sanki kutu boşmuş gibi
             <button type="button" id="undo_redo_rightAll" class="btn btn-default btn-block"> >> </button>  -->
        <button type="button" id="undo_redo_rightSelected" class="btn btn-default btn-block"> --> </i></button>
        <button type="button" id="undo_redo_leftSelected" class="btn btn-default btn-block"> <-- </button>
        <!-- <button type="button" id="undo_redo_leftAll" class="btn btn-default btn-block"> << </button>   -->
        <button type="button" id="undo_redo_redo" class="btn btn-warning btn-block">redo</button>
      </div>
      <div class="col-sm-2">
          Seçilmiş ürünler
        <select name="to" id="undo_redo_to" class="form-control" size="8" multiple="multiple"></select>
      </div>
      <div  class="col-sm-2">

            Sipariş Tipi
          <select name="order_type" class="select form-control" required="" id="id_order_type">
            <option value="" selected="">---------</option>
            <option value="U">Uretim</option>
            <option value="S">Sevk</option>
            <option value="M">Montaj</option>
            <option value="D">Depo Teslim</option>
          </select>
          <br>
          Üretim
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="uretim" id="inlineRadio1" value="1">
            <label class="form-check-label" for="inlineRadio1">Var</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="uretim" id="inlineRadio2" value="0">
            <label class="form-check-label" for="inlineRadio2">Yok</label>
          </div>

      </div>


      
      <div  class="d-grid gap-2 col-2 mx-auto">
            {% if order.siparis_paketi == False %}
                <button class="btn btn-primary" >Sipariş paketi oluştur</button>
            {% endif %}
      </div>
    </div>
  </div>

</form>
<hr><br>

<div class="table-full-width table-responsive px-0 card-body">
      
    {% if products_selected %}
    Sipariş Grupları
    <table class="table-hover table-striped table">
      <thead>
        <tr>
          <th class="border-0" scope="col">ID</th>
          <th class="border-0" scope="col">Ürün</th>
          <th class="border-0" scope="col">Paket ID</th>
          <th class="border-0" scope="col">Sipariş Tipi</th>
          <th class="border-0" scope="col">Üretim</th>
          <th class="border-0" scope="col"></th>
          
        </tr>
      </thead>
      <tbody>
          {% for packet in products_selected %}
            <tr>
              <td scope="row">{{packet.id}}</td>
              <td>{{packet.product.product_name}}</td>
              <td>{{packet.orderpackets.id}}</td>
              <td>{{packet.orderpackets.order_type}}</td>
              <td>
                {% if packet.orderpackets.uretim %}
                  Var
                {%else%}
                  Yok
                {%endif%}
                
              </td>
              <td>
                <div class="dropdown">
                    {% if order.siparis_paketi == False %}
                    <a class="dropdown-item" href="/order/orderPacketDelete/{{packet.id}}"><button class="btn btn-outline-info" type="button">
                        Sil
                    </button></a>
                    {% endif %}
                  
                </div>
                
            </tr>
          {% endfor %}
        
    
      </tbody>
    </table>
  {%else%}
    <div class="alert alert-danger">
        Sipariş Paketi oluşturulmamış!!!
    </div>
  {% endif %}
</div>
<div class="col-sm-10 ">
    {% if products.count == 0%}
        <a href="/order/orderPaketOnayla/{{order.id}}/{{workflow_id}}"><button class="btn btn-danger" > Sipariş paketlerini Onayla  </button></a>
    {% endif %}
</div>

<br><br><br>
<script src="https://www.jqueryscript.net/demo/Two-side-Multi-Select-Plugin-with-jQuery-multiselect-js/js/multiselect.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#undo_redo').multiselect();
  });
    
</script>
    
{% endblock body %}